# Generated by Django 2.1.7 on 2019-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
    ]
