# Generated by Django 2.1.7 on 2019-05-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_endereco_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='telefone',
        ),
    ]
