# Generated by Django 2.1.7 on 2019-05-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='assinaturas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
    ]
