# Generated by Django 2.1.7 on 2019-05-13 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20190503_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf_cnpj',
            new_name='cpf',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
