# Generated by Django 2.1.7 on 2019-04-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0002_auto_20190429_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sazonalidade', models.CharField(max_length=45)),
                ('data_pagamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('produtos', models.ManyToManyField(to='producao.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='assinatura',
            name='pacotes',
            field=models.ManyToManyField(to='assinatura.Pacote'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='tipo_pagamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='assinatura.TipoPagamento'),
        ),
    ]
