# Generated by Django 2.1.7 on 2019-04-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quantidade', models.IntegerField()),
                ('cooperativa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cooperativa.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=25)),
                ('un_medida', models.CharField(max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_produtos')),
            ],
        ),
        migrations.AddField(
            model_name='producao',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='producao.Produto'),
        ),
    ]
