# Generated by Django 2.1.7 on 2019-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
